[package]
name = "server"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
actix-web = "4"
serde = { version = "1.0.208", features = ["derive"] }
chrono = "0.4.38"
base64 = "0.22.1"

[dependencies.altcha-lib-rs]
default-features = true
path = "../.."
